from enum import StrEnum


class EventType(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    OTP_ABUSE_ATTEMPT = "OTP_ABUSE_ATTEMPT"
    REGISTRATION = "REGISTRATION"
    API_REQUEST = "API_REQUEST"
    PASSWORD_RESET = "PASSWORD_RESET"  # nosec B105
    OTP_SENT = "OTP_SENT"
    EMAIL_SENT = "EMAIL_SENT"
    EMAIL_FAILED = "EMAIL_FAILED"
    TENANT_ONBOARDED = "TENANT_ONBOARDED"
    PROJECT_CREATED = "PROJECT_CREATED"
    API_KEY_ROTATED = "API_KEY_ROTATED"
    JWT_KEY_ROTATED = "JWT_KEY_ROTATED"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
