from enum import StrEnum


class EventType(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    OTP_ABUSE_ATTEMPT = "OTP_ABUSE_ATTEMPT"
    REGISTRATION = "REGISTRATION"
    API_REQUEST = "API_REQUEST"
    PASSWORD_RESET = "PASSWORD_RESET"  # nosec B105
    OTP_SENT = "OTP_SENT"
