from typing import Protocol, Sequence
from uuid import UUID

from src.modules.projects.domain.entities import ProjectEntity


class ProjectQueryRepositoryPort(Protocol):
    async def get_by_id(self, project_id: UUID) -> ProjectEntity | None: ...
    async def get_by_api_key_hash(self, api_key_hash: str) -> ProjectEntity | None: ...
    async def get_by_name(self, name: str) -> ProjectEntity | None: ...
    async def get_all_for_tenant(self, tenant_id: UUID) -> Sequence[ProjectEntity]: ...
    async def get_private_key(self, project_id: UUID) -> str | None: ...
