name: cerberus

networks:
  cerberus_network:
    driver: bridge

services:
  cerb-postgres:
    image: postgres:18
    container_name: cerb-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: [ "postgres", "-p", "52193" ]
    volumes:
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 52193 -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cerberus_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cerb-redis:
    image: redis:8.8.0
    container_name: cerb-redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.acl:/mnt/users.acl:ro
    command: [ "redis-server", "--port", "52192", "--aclfile", "/mnt/users.acl" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p 52192 ping | grep -E '(PONG|NOAUTH)'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cerberus_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cerb-lb:
    image: nginx:1.31.2-alpine
    container_name: cerb-lb
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      cerb-vite:
        condition: service_healthy
      cerb-fastapi:
        condition: service_healthy
    networks:
      - cerberus_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cerb-fastapi:
    image: avneesh11905/cerberus-fastapi:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      cerb-postgres:
        condition: service_healthy
      cerb-redis:
        condition: service_healthy
    volumes:
      # JWT RSA Keys folder (Generated by `uv run backend/scripts/generate_keys.py`)
      - ./backend/keys:/app/keys:ro
    expose:
      - "8000"
    networks:
      - cerberus_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cerb-celery-worker:
    image: avneesh11905/cerberus-fastapi:latest
    restart: unless-stopped
    command: celery -A src.shared.adapters.task_runner.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      cerb-postgres:
        condition: service_healthy
      cerb-redis:
        condition: service_healthy
    volumes:
      # JWT RSA Keys folder (Generated by `uv run backend/scripts/generate_keys.py`)
      - ./backend/keys:/app/keys:ro
    networks:
      - cerberus_network
    healthcheck:
      test: [ "CMD-SHELL", "celery -A src.shared.adapters.task_runner.celery_app inspect ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cerb-vite:
    image: avneesh11905/cerberus-vite:latest
    restart: unless-stopped
    depends_on:
      cerb-fastapi:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - cerberus_network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pidof nginx || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"
