import os
import re
import urllib.parse
import getpass

def update_or_create_env(env_path, user, password_raw):
    # url-encode the password for the connection strings and env var
    password_encoded = urllib.parse.quote(password_raw, safe='')
    
    if os.path.exists(env_path):
        with open(env_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Update REDIS_USER and REDIS_PASSWORD
        if re.search(r'^REDIS_USER=.*$', content, flags=re.MULTILINE):
            content = re.sub(r'^REDIS_USER=.*$', f'REDIS_USER={user}', content, flags=re.MULTILINE)
        else:
            content += f'\nREDIS_USER={user}\n'
            
        if re.search(r'^REDIS_PASSWORD=.*$', content, flags=re.MULTILINE):
            content = re.sub(r'^REDIS_PASSWORD=.*$', f'REDIS_PASSWORD={password_encoded}', content, flags=re.MULTILINE)
        else:
            content += f'REDIS_PASSWORD={password_encoded}\n'

        # Optional: update connection strings if they exist
        content = re.sub(r'^(CACHE_URL=redis://)[^@]+(@.*)$', fr'\g<1>{user}:{password_encoded}\g<2>', content, flags=re.MULTILINE)
        content = re.sub(r'^(CELERY_BROKER_URL=redis://)[^@]+(@.*)$', fr'\g<1>{user}:{password_encoded}\g<2>', content, flags=re.MULTILINE)
        content = re.sub(r'^(CELERY_RESULT_BACKEND=redis://)[^@]+(@.*)$', fr'\g<1>{user}:{password_encoded}\g<2>', content, flags=re.MULTILINE)
            
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {env_path}")
    else:
        # Create new .env
        content = f"""
REDIS_USER={user}
REDIS_PASSWORD={password_encoded}
CACHE_URL=redis://{user}:{password_encoded}@cerb-redis:52192/0
CELERY_BROKER_URL=redis://{user}:{password_encoded}@cerb-redis:52192/1
CELERY_RESULT_BACKEND=redis://{user}:{password_encoded}@cerb-redis:52192/2

"""
        os.makedirs(os.path.dirname(env_path), exist_ok=True)
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Created {env_path}")

def generate_acl_file(output_path, user, password_raw):
    acl_content = f"""
# Redis ACL file
# This file is automatically generated. Do not edit manually.

# Disable the default user for security
user default off nopass nocommands

# Application user
user {user} on >{password_raw} ~* &* +@all
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(acl_content)
    print(f"Successfully generated {output_path} for user '{user}'.")

def main():
    print("=== Redis ACL Generator ===")
    user = input("Enter Redis username [default: cerberus]: ").strip()
    if not user:
        user = "cerberus"
        
    password_raw = getpass.getpass("Enter Redis password: ").strip()
    while not password_raw:
        print("Password cannot be empty.")
        password_raw = getpass.getpass("Enter Redis password: ").strip()

    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    deploy_dir = os.path.join(os.path.dirname(base_dir), 'deploy_script')
    
    # 1. cerberus folder
    cerberus_env = os.path.join(base_dir, '.env')
    cerberus_acl = os.path.join(base_dir, 'redis', 'redis.acl')
    update_or_create_env(cerberus_env, user, password_raw)
    generate_acl_file(cerberus_acl, user, password_raw)

    # 2. deploy_script folder
    deploy_env = os.path.join(deploy_dir, '.env')
    deploy_acl = os.path.join(deploy_dir, 'redis', 'redis.acl')
    
    # Only update deploy_script if the directory exists
    if os.path.exists(deploy_dir):
        update_or_create_env(deploy_env, user, password_raw)
        generate_acl_file(deploy_acl, user, password_raw)
    else:
        print(f"Deploy script directory not found at {deploy_dir}, skipping.")

if __name__ == '__main__':
    main()
