"""initial_migration

Revision ID: 047b89e56785
Revises:
Create Date: 2026-07-19 03:01:28.642280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "047b89e56785"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "LOGIN_SUCCESS",
                "LOGIN_FAILED",
                "OTP_ABUSE_ATTEMPT",
                "REGISTRATION",
                "API_REQUEST",
                "PASSWORD_RESET",
                "OTP_SENT",
                name="event_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_events_event_type"),
        "analytics_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_project_id"),
        "analytics_events",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_tenant_id"),
        "analytics_events",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_timestamp"),
        "analytics_events",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "daily_project_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("api_requests", sa.Integer(), nullable=False),
        sa.Column("login_successes", sa.Integer(), nullable=False),
        sa.Column("login_failures", sa.Integer(), nullable=False),
        sa.Column("registrations", sa.Integer(), nullable=False),
        sa.Column("active_users", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "date", name="uq_project_date"),
    )
    op.create_index(
        op.f("ix_daily_project_metrics_project_id"),
        "daily_project_metrics",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "daily_tenant_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("api_requests", sa.Integer(), nullable=False),
        sa.Column("login_successes", sa.Integer(), nullable=False),
        sa.Column("login_failures", sa.Integer(), nullable=False),
        sa.Column("registrations", sa.Integer(), nullable=False),
        sa.Column("active_users", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "date", name="uq_tenant_date"),
    )
    op.create_index(
        op.f("ix_daily_tenant_metrics_tenant_id"),
        "daily_tenant_metrics",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("file", sa.String(), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_logs_created_at"), "system_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_source"), "system_logs", ["source"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "receive_updates",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "role",
            sa.Enum("SUPERADMIN", "TENANT", name="globalrole"),
            server_default=sa.text("'TENANT'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_active_tenants",
        "tenants",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.create_index(op.f("ix_tenants_email"), "tenants", ["email"], unique=False)
    op.create_index("uq_tenant_email", "tenants", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("admin_email", sa.String(), nullable=True),
        sa.Column("private_key", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column(
            "oauth_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_origins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "default_claims",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "environment",
            sa.String(),
            server_default=sa.text("'development'"),
            nullable=False,
        ),
        sa.Column("frontend_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_allowed_origins_gin",
        "projects",
        ["allowed_origins"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_projects_api_key_hash"), "projects", ["api_key_hash"], unique=True
    )
    op.create_index(
        op.f("ix_projects_tenant_id"), "projects", ["tenant_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "receive_updates",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column(
            "custom_claims",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_active_users",
        "users",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.create_index(
        "idx_users_custom_claims_gin",
        "users",
        ["custom_claims"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_project_id"), "users", ["project_id"], unique=False)
    op.create_index("uq_project_email", "users", ["email", "project_id"], unique=True)
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("oauth_sub", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(tenant_id IS NOT NULL AND user_id IS NULL) OR (tenant_id IS NULL AND user_id IS NOT NULL)",
            name="chk_oauth_account_owner",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_accounts_tenant_id"),
        "oauth_accounts",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False
    )
    op.create_index(
        "uq_tenant_provider_oauth_sub",
        "oauth_accounts",
        ["provider", "oauth_sub", "tenant_id"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )
    op.create_index(
        "uq_user_provider_oauth_sub",
        "oauth_accounts",
        ["provider", "oauth_sub", "user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "passwords",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(tenant_id IS NOT NULL AND user_id IS NULL) OR (tenant_id IS NULL AND user_id IS NOT NULL)",
            name="chk_password_owner",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passwords_tenant_id"), "passwords", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_passwords_user_id"), "passwords", ["user_id"], unique=False
    )
    op.create_index(
        "uq_tenant_password",
        "passwords",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )
    op.create_index(
        "uq_user_password",
        "passwords",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("auth_provider", sa.String(), server_default="local", nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(tenant_id IS NOT NULL AND user_id IS NULL) OR (tenant_id IS NULL AND user_id IS NOT NULL)",
            name="chk_refresh_token_owner",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_tenant_id"),
        "refresh_tokens",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "uq_user_password",
        table_name="passwords",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_tenant_password",
        table_name="passwords",
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_passwords_user_id"), table_name="passwords")
    op.drop_index(op.f("ix_passwords_tenant_id"), table_name="passwords")
    op.drop_table("passwords")
    op.drop_index(
        "uq_user_provider_oauth_sub",
        table_name="oauth_accounts",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_tenant_provider_oauth_sub",
        table_name="oauth_accounts",
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_tenant_id"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index("uq_project_email", table_name="users")
    op.drop_index(op.f("ix_users_project_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(
        "idx_users_custom_claims_gin", table_name="users", postgresql_using="gin"
    )
    op.drop_index(
        "idx_active_users",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_tenant_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_api_key_hash"), table_name="projects")
    op.drop_index(
        "idx_allowed_origins_gin", table_name="projects", postgresql_using="gin"
    )
    op.drop_table("projects")
    op.drop_index("uq_tenant_email", table_name="tenants")
    op.drop_index(op.f("ix_tenants_email"), table_name="tenants")
    op.drop_index(
        "idx_active_tenants",
        table_name="tenants",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.drop_table("tenants")
    op.drop_index(op.f("ix_system_logs_source"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_created_at"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(
        op.f("ix_daily_tenant_metrics_tenant_id"), table_name="daily_tenant_metrics"
    )
    op.drop_table("daily_tenant_metrics")
    op.drop_index(
        op.f("ix_daily_project_metrics_project_id"), table_name="daily_project_metrics"
    )
    op.drop_table("daily_project_metrics")
    op.drop_index(op.f("ix_analytics_events_timestamp"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_tenant_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_project_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_type"), table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
