"""use native enums and project_user fixes

Revision ID: 304e4309fb10
Revises: 3f60c6b03f32
Create Date: 2026-07-26 01:39:02.426844

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "304e4309fb10"
down_revision: Union[str, Sequence[str], None] = "3f60c6b03f32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
