"""remove_admin_email_from_projects

Revision ID: 37ecaa6de16b
Revises: 047b89e56785
Create Date: 2026-07-20 02:29:19.768494

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37ecaa6de16b"
down_revision: Union[str, Sequence[str], None] = "047b89e56785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "admin_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("admin_email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
