"""Add new telemetry columns and system metrics

Revision ID: 50bd77d031d0
Revises: 37ecaa6de16b
Create Date: 2026-07-22 18:24:56.681845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bd77d031d0'
down_revision: Union[str, Sequence[str], None] = '37ecaa6de16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum values manually
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'EMAIL_SENT'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'EMAIL_FAILED'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'TENANT_ONBOARDED'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'PROJECT_CREATED'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'API_KEY_ROTATED'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'JWT_KEY_ROTATED'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'TENANT_SUSPENDED'")
    op.create_table('daily_system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tenants_onboarded', sa.Integer(), nullable=False),
    sa.Column('tenant_suspensions', sa.Integer(), nullable=False),
    sa.Column('api_key_rotations', sa.Integer(), nullable=False),
    sa.Column('jwt_key_rotations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_system_date')
    )
    op.create_index(op.f('ix_daily_system_metrics_date'), 'daily_system_metrics', ['date'], unique=False)
    op.add_column('daily_project_metrics', sa.Column('emails_sent', sa.Integer(), nullable=False))
    op.add_column('daily_project_metrics', sa.Column('emails_failed', sa.Integer(), nullable=False))
    op.add_column('daily_tenant_metrics', sa.Column('emails_sent', sa.Integer(), nullable=False))
    op.add_column('daily_tenant_metrics', sa.Column('emails_failed', sa.Integer(), nullable=False))
    op.add_column('daily_tenant_metrics', sa.Column('projects_created', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_tenant_metrics', 'projects_created')
    op.drop_column('daily_tenant_metrics', 'emails_failed')
    op.drop_column('daily_tenant_metrics', 'emails_sent')
    op.drop_column('daily_project_metrics', 'emails_failed')
    op.drop_column('daily_project_metrics', 'emails_sent')
    op.drop_index(op.f('ix_daily_system_metrics_date'), table_name='daily_system_metrics')
    op.drop_table('daily_system_metrics')
    # ### end Alembic commands ###
