"""schema optimizations

Revision ID: 7734c7cf9f64
Revises: 4e48786a50fc
Create Date: 2026-07-09 16:16:42.027989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7734c7cf9f64'
down_revision: Union[str, Sequence[str], None] = '4e48786a50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_allowed_origins_gin', 'projects', ['allowed_origins'], unique=False, postgresql_using='gin')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'TENANT', 'USER', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.create_index('idx_active_users', 'users', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_active_users', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'TENANT', 'USER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.drop_index('idx_allowed_origins_gin', table_name='projects', postgresql_using='gin')
    # ### end Alembic commands ###
