"""Initial migration

Revision ID: ccd02348c5de
Revises:
Create Date: 2026-06-20 00:51:50.901372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.shared.infrastructure.sql.tables


# revision identifiers, used by Alembic.
revision: str = "ccd02348c5de"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("file", sa.String(), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_logs_created_at"), "system_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_source"), "system_logs", ["source"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "receive_updates",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "role", sa.String(), server_default=sa.text("'user'"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_project_id"), "users", ["project_id"], unique=False)
    op.create_index(
        "uq_project_email",
        "users",
        ["email", "project_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        "uq_tenant_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("private_key", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column(
            "oauth_config",
            src.shared.infrastructure.sql.tables.SQLiteCompatibleJSON(),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_origins",
            src.shared.infrastructure.sql.tables.SQLiteCompatibleJSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "environment",
            sa.String(),
            server_default=sa.text("'development'"),
            nullable=False,
        ),
        sa.Column("frontend_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_api_key_hash"), "projects", ["api_key_hash"], unique=True
    )
    op.create_index(
        op.f("ix_projects_tenant_id"), "projects", ["tenant_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("auth_provider", sa.String(), server_default="local", nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_active_sessions",
        "refresh_tokens",
        ["user_id", "used", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_passwords",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_passwords_user_id"), "user_passwords", ["user_id"], unique=True
    )
    op.create_table(
        "user_oauth_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("oauth_sub", sa.String(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_oauth_accounts_project_id"),
        "user_oauth_accounts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_oauth_accounts_user_id"),
        "user_oauth_accounts",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_project_provider_oauth_sub",
        "user_oauth_accounts",
        ["provider", "oauth_sub", "project_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        "uq_tenant_provider_oauth_sub",
        "user_oauth_accounts",
        ["provider", "oauth_sub"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_tenant_provider_oauth_sub",
        table_name="user_oauth_accounts",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        "uq_project_provider_oauth_sub",
        table_name="user_oauth_accounts",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_user_oauth_accounts_user_id"), table_name="user_oauth_accounts"
    )
    op.drop_index(
        op.f("ix_user_oauth_accounts_project_id"), table_name="user_oauth_accounts"
    )
    op.drop_table("user_oauth_accounts")
    op.drop_index(op.f("ix_user_passwords_user_id"), table_name="user_passwords")
    op.drop_table("user_passwords")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_index("idx_active_sessions", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_projects_tenant_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_api_key_hash"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        "uq_tenant_email",
        table_name="users",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        "uq_project_email",
        table_name="users",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_users_project_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_logs_source"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_created_at"), table_name="system_logs")
    op.drop_table("system_logs")
    # ### end Alembic commands ###
