/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSetupRouteImport } from './routes/docs.setup'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedAdminRouteImport } from './routes/_protected.admin'
import { Route as DocsSdkIndexRouteImport } from './routes/docs.sdk.index'
import { Route as DocsSdkUsersRouteImport } from './routes/docs.sdk.users'
import { Route as DocsSdkReferenceRouteImport } from './routes/docs.sdk.reference'
import { Route as DocsSdkReactRouteImport } from './routes/docs.sdk.react'
import { Route as DocsSdkAuthRouteImport } from './routes/docs.sdk.auth'
import { Route as ProtectedProjectsProjectIdRouteImport } from './routes/_protected.projects.$projectId'
import { Route as ProtectedAdminTenantsRouteImport } from './routes/_protected.admin.tenants'
import { Route as ProtectedAdminLogsRouteImport } from './routes/_protected.admin.logs'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSetupRoute = DocsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const DocsSdkIndexRoute = DocsSdkIndexRouteImport.update({
  id: '/sdk/',
  path: '/sdk/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkUsersRoute = DocsSdkUsersRouteImport.update({
  id: '/sdk/users',
  path: '/sdk/users',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkReferenceRoute = DocsSdkReferenceRouteImport.update({
  id: '/sdk/reference',
  path: '/sdk/reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkReactRoute = DocsSdkReactRouteImport.update({
  id: '/sdk/react',
  path: '/sdk/react',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkAuthRoute = DocsSdkAuthRouteImport.update({
  id: '/sdk/auth',
  path: '/sdk/auth',
  getParentRoute: () => DocsRoute,
} as any)
const ProtectedProjectsProjectIdRoute =
  ProtectedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminTenantsRoute = ProtectedAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminLogsRoute = ProtectedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProtectedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/logs': typeof ProtectedAdminLogsRoute
  '/admin/tenants': typeof ProtectedAdminTenantsRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/docs/sdk/auth': typeof DocsSdkAuthRoute
  '/docs/sdk/react': typeof DocsSdkReactRoute
  '/docs/sdk/reference': typeof DocsSdkReferenceRoute
  '/docs/sdk/users': typeof DocsSdkUsersRoute
  '/docs/sdk/': typeof DocsSdkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs': typeof DocsIndexRoute
  '/admin/logs': typeof ProtectedAdminLogsRoute
  '/admin/tenants': typeof ProtectedAdminTenantsRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/docs/sdk/auth': typeof DocsSdkAuthRoute
  '/docs/sdk/react': typeof DocsSdkReactRoute
  '/docs/sdk/reference': typeof DocsSdkReferenceRoute
  '/docs/sdk/users': typeof DocsSdkUsersRoute
  '/docs/sdk': typeof DocsSdkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/': typeof DocsIndexRoute
  '/_protected/admin/logs': typeof ProtectedAdminLogsRoute
  '/_protected/admin/tenants': typeof ProtectedAdminTenantsRoute
  '/_protected/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/docs/sdk/auth': typeof DocsSdkAuthRoute
  '/docs/sdk/react': typeof DocsSdkReactRoute
  '/docs/sdk/reference': typeof DocsSdkReferenceRoute
  '/docs/sdk/users': typeof DocsSdkUsersRoute
  '/docs/sdk/': typeof DocsSdkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/docs/architecture'
    | '/docs/setup'
    | '/docs/'
    | '/admin/logs'
    | '/admin/tenants'
    | '/projects/$projectId'
    | '/docs/sdk/auth'
    | '/docs/sdk/react'
    | '/docs/sdk/reference'
    | '/docs/sdk/users'
    | '/docs/sdk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/docs/architecture'
    | '/docs/setup'
    | '/docs'
    | '/admin/logs'
    | '/admin/tenants'
    | '/projects/$projectId'
    | '/docs/sdk/auth'
    | '/docs/sdk/react'
    | '/docs/sdk/reference'
    | '/docs/sdk/users'
    | '/docs/sdk'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/docs'
    | '/forgot-password'
    | '/reset-password'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/docs/architecture'
    | '/docs/setup'
    | '/docs/'
    | '/_protected/admin/logs'
    | '/_protected/admin/tenants'
    | '/_protected/projects/$projectId'
    | '/docs/sdk/auth'
    | '/docs/sdk/react'
    | '/docs/sdk/reference'
    | '/docs/sdk/users'
    | '/docs/sdk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/setup': {
      id: '/docs/setup'
      path: '/setup'
      fullPath: '/docs/setup'
      preLoaderRoute: typeof DocsSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/docs/sdk/': {
      id: '/docs/sdk/'
      path: '/sdk'
      fullPath: '/docs/sdk/'
      preLoaderRoute: typeof DocsSdkIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk/users': {
      id: '/docs/sdk/users'
      path: '/sdk/users'
      fullPath: '/docs/sdk/users'
      preLoaderRoute: typeof DocsSdkUsersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk/reference': {
      id: '/docs/sdk/reference'
      path: '/sdk/reference'
      fullPath: '/docs/sdk/reference'
      preLoaderRoute: typeof DocsSdkReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk/react': {
      id: '/docs/sdk/react'
      path: '/sdk/react'
      fullPath: '/docs/sdk/react'
      preLoaderRoute: typeof DocsSdkReactRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk/auth': {
      id: '/docs/sdk/auth'
      path: '/sdk/auth'
      fullPath: '/docs/sdk/auth'
      preLoaderRoute: typeof DocsSdkAuthRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_protected/projects/$projectId': {
      id: '/_protected/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/tenants': {
      id: '/_protected/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof ProtectedAdminTenantsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/logs': {
      id: '/_protected/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof ProtectedAdminLogsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminLogsRoute: typeof ProtectedAdminLogsRoute
  ProtectedAdminTenantsRoute: typeof ProtectedAdminTenantsRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminLogsRoute: ProtectedAdminLogsRoute,
  ProtectedAdminTenantsRoute: ProtectedAdminTenantsRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedProjectsProjectIdRoute: typeof ProtectedProjectsProjectIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedProjectsProjectIdRoute: ProtectedProjectsProjectIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsSetupRoute: typeof DocsSetupRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsSdkAuthRoute: typeof DocsSdkAuthRoute
  DocsSdkReactRoute: typeof DocsSdkReactRoute
  DocsSdkReferenceRoute: typeof DocsSdkReferenceRoute
  DocsSdkUsersRoute: typeof DocsSdkUsersRoute
  DocsSdkIndexRoute: typeof DocsSdkIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsSetupRoute: DocsSetupRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsSdkAuthRoute: DocsSdkAuthRoute,
  DocsSdkReactRoute: DocsSdkReactRoute,
  DocsSdkReferenceRoute: DocsSdkReferenceRoute,
  DocsSdkUsersRoute: DocsSdkUsersRoute,
  DocsSdkIndexRoute: DocsSdkIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
