/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedSuperadminRouteImport } from './routes/_protected.superadmin'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected.projects.index'
import { Route as ProtectedSuperadminIndexRouteImport } from './routes/_protected.superadmin.index'
import { Route as ProtectedSuperadminLogsRouteImport } from './routes/_protected.superadmin.logs'
import { Route as ProtectedSuperadminTenantsRouteImport } from './routes/_protected.superadmin.tenants'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected.users.index'
import { Route as ProtectedProjectsProjectIdIndexRouteImport } from './routes/_protected.projects.$projectId.index'
import { Route as ProtectedProjectsProjectIdSettingsRouteImport } from './routes/_protected.projects.$projectId.settings'
import { Route as ProtectedSuperadminTenantsTenantIdAnalyticsRouteImport } from './routes/_protected.superadmin.tenants_.$tenantId.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSuperadminRoute = ProtectedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => ProtectedRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSuperadminIndexRoute =
  ProtectedSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSuperadminRoute,
  } as any)
const ProtectedSuperadminLogsRoute = ProtectedSuperadminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProtectedSuperadminRoute,
} as any)
const ProtectedSuperadminTenantsRoute =
  ProtectedSuperadminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => ProtectedSuperadminRoute,
  } as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsProjectIdIndexRoute =
  ProtectedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProjectsProjectIdSettingsRoute =
  ProtectedProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSuperadminTenantsTenantIdAnalyticsRoute =
  ProtectedSuperadminTenantsTenantIdAnalyticsRouteImport.update({
    id: '/tenants_/$tenantId/analytics',
    path: '/tenants/$tenantId/analytics',
    getParentRoute: () => ProtectedSuperadminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/superadmin': typeof ProtectedSuperadminRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/superadmin/logs': typeof ProtectedSuperadminLogsRoute
  '/superadmin/tenants': typeof ProtectedSuperadminTenantsRoute
  '/projects/': typeof ProtectedProjectsIndexRoute
  '/superadmin/': typeof ProtectedSuperadminIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
  '/superadmin/tenants/$tenantId/analytics': typeof ProtectedSuperadminTenantsTenantIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/superadmin/logs': typeof ProtectedSuperadminLogsRoute
  '/superadmin/tenants': typeof ProtectedSuperadminTenantsRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/superadmin': typeof ProtectedSuperadminIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
  '/superadmin/tenants/$tenantId/analytics': typeof ProtectedSuperadminTenantsTenantIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/superadmin': typeof ProtectedSuperadminRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/_protected/superadmin/logs': typeof ProtectedSuperadminLogsRoute
  '/_protected/superadmin/tenants': typeof ProtectedSuperadminTenantsRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/superadmin/': typeof ProtectedSuperadminIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/_protected/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
  '/_protected/superadmin/tenants_/$tenantId/analytics': typeof ProtectedSuperadminTenantsTenantIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/superadmin'
    | '/oauth/callback'
    | '/superadmin/logs'
    | '/superadmin/tenants'
    | '/projects/'
    | '/superadmin/'
    | '/users/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/superadmin/tenants/$tenantId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/oauth/callback'
    | '/superadmin/logs'
    | '/superadmin/tenants'
    | '/projects'
    | '/superadmin'
    | '/users'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/superadmin/tenants/$tenantId/analytics'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/_protected/superadmin'
    | '/oauth/callback'
    | '/_protected/superadmin/logs'
    | '/_protected/superadmin/tenants'
    | '/_protected/projects/'
    | '/_protected/superadmin/'
    | '/_protected/users/'
    | '/_protected/projects/$projectId/settings'
    | '/_protected/projects/$projectId/'
    | '/_protected/superadmin/tenants_/$tenantId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/superadmin': {
      id: '/_protected/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof ProtectedSuperadminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/superadmin/': {
      id: '/_protected/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof ProtectedSuperadminIndexRouteImport
      parentRoute: typeof ProtectedSuperadminRoute
    }
    '/_protected/superadmin/logs': {
      id: '/_protected/superadmin/logs'
      path: '/logs'
      fullPath: '/superadmin/logs'
      preLoaderRoute: typeof ProtectedSuperadminLogsRouteImport
      parentRoute: typeof ProtectedSuperadminRoute
    }
    '/_protected/superadmin/tenants': {
      id: '/_protected/superadmin/tenants'
      path: '/tenants'
      fullPath: '/superadmin/tenants'
      preLoaderRoute: typeof ProtectedSuperadminTenantsRouteImport
      parentRoute: typeof ProtectedSuperadminRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/$projectId/': {
      id: '/_protected/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/$projectId/settings': {
      id: '/_protected/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProtectedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/superadmin/tenants_/$tenantId/analytics': {
      id: '/_protected/superadmin/tenants_/$tenantId/analytics'
      path: '/tenants/$tenantId/analytics'
      fullPath: '/superadmin/tenants/$tenantId/analytics'
      preLoaderRoute: typeof ProtectedSuperadminTenantsTenantIdAnalyticsRouteImport
      parentRoute: typeof ProtectedSuperadminRoute
    }
  }
}

interface ProtectedSuperadminRouteChildren {
  ProtectedSuperadminLogsRoute: typeof ProtectedSuperadminLogsRoute
  ProtectedSuperadminTenantsRoute: typeof ProtectedSuperadminTenantsRoute
  ProtectedSuperadminIndexRoute: typeof ProtectedSuperadminIndexRoute
  ProtectedSuperadminTenantsTenantIdAnalyticsRoute: typeof ProtectedSuperadminTenantsTenantIdAnalyticsRoute
}

const ProtectedSuperadminRouteChildren: ProtectedSuperadminRouteChildren = {
  ProtectedSuperadminLogsRoute: ProtectedSuperadminLogsRoute,
  ProtectedSuperadminTenantsRoute: ProtectedSuperadminTenantsRoute,
  ProtectedSuperadminIndexRoute: ProtectedSuperadminIndexRoute,
  ProtectedSuperadminTenantsTenantIdAnalyticsRoute:
    ProtectedSuperadminTenantsTenantIdAnalyticsRoute,
}

const ProtectedSuperadminRouteWithChildren =
  ProtectedSuperadminRoute._addFileChildren(ProtectedSuperadminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSuperadminRoute: typeof ProtectedSuperadminRouteWithChildren
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedProjectsProjectIdSettingsRoute: typeof ProtectedProjectsProjectIdSettingsRoute
  ProtectedProjectsProjectIdIndexRoute: typeof ProtectedProjectsProjectIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSuperadminRoute: ProtectedSuperadminRouteWithChildren,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedProjectsProjectIdSettingsRoute:
    ProtectedProjectsProjectIdSettingsRoute,
  ProtectedProjectsProjectIdIndexRoute: ProtectedProjectsProjectIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
